name: Cypress Tests - Smoke Flow

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install TypeScript
        working-directory: ./e2e-tests
        run: |
          pwd
          cat package.json
          npm install typescript --save-dev
          cat package.json
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/smoke/*
          browser: chrome
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: |
            cypress/screenshots
            cypress/videos